### ISSUE TITLE
Create HelloWorld SpringBoot  code

### ISSUE THREAD

**Issue by academyExcelleance** [academyExcelleance/springboot-tutorial#1]
Reference Link

https://www.geeksforgeeks.org/how-to-run-your-first-spring-boot-application-in-intellij-idea/?ref=asr1

**Comment by ipsi1999644** [comment]
dcdddddddddddddd

**Comment by ipsi1999644** [comment]
1. To Develop a web Application with spring boot and Maven, need to be added spring-boot-starter-web dependency in pom.xml
2. Create a  java class with the name controller(AcademicController.java) and need to add a class level annotation @RestController. This annotation means this class will be picked up by the component scan, because it's in the same package as our AcademicApplication class. 
3. To create mapping method we use @RequestMapping annotation at the class.
